baseURL = "/"
languageCode = "en-us"
title = "olehermanse"
theme = "minimal"
Paginate = 5
appendPort = false
port = 80
enableRobotsTXT = true

[params.social]
    twitter = "olehermanse"
    github = "olehermanse"
    email = "oleherman93@gmail.com"
    linkedin = "olehermanse"
    facebook = "olehermanse"
    instagram = "olehermanse"

[params]
    author = "Ole Herman Schumacher Elgesem"
    description = "/dev/null"
    githubUsername = "olehermanse"
    accent = "teal"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "rust", "js", "c", "html", "css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

# [[menu.main]]
#     url = "/projects/"
#     name = "Projects"
#     weight = 3

# [[menu.main]]
#     url = "/articles/"
#     name = "Articles"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:oleherman93@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/olehermanse/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/olehermanse/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/olehermanse/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.instagram.com/olehermanse/"
    name = "instagram"
    weight = 5

[[menu.icon]]
    url = "https://medium.com/@olehermanse"
    name = "medium"
    weight = 6

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
