baseURL = "/"
languageCode = "en-us"
title = "olehermanse"
theme = "kiss"
Paginate = 5
appendPort = false
port = 80
enableRobotsTXT = true

[params.social]

twitter = "olehermanse"
github = "olehermanse"
email = "oleherman93@gmail.com"
linkedin = "olehermanse"
facebook = "olehermanse"
instagram = "olehermanse"
