baseurl = "/"
languageCode = "en"
title = "olehermanse"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/olehermanse\">Ole Herman Schumacher Elgesem</a> 2018"
# Number of posts per page
Paginate = 10
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Ole Herman S. Elgesem" # Author full name
authorEmail = "oleherman93@gmail.com" # Author email

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "olehermanse" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.sections_left]
"/unix/" = "UNIX"
"/gamedev/" = "GameDev"
"/about" = "About"

[params.social]
twitter = "olehermanse"
instagram = "olehermanse"
email = "oleherman93@gmail.com"
linkedin = "olehermanse"
gitlab = "olehermanse"
github = "olehermanse"

[params.social.config]
platforms = ["instagram", "email", "linkedin", "gitlab", "github", "twitter"]

[taxonomies]
tag = "tags"
